_GCP_PROJECT_ID: "closeracademy-handson"
_GCS_BUCKET_NAME_MODELS: "your_name_in_lowercase-models"
_BIGQUERY_DATASET_ID: "your_name_in_lowercase_titanic"
_BIGQUERY_TABLE_ID: "titanic_predictions"
_MODEL_LOCATION: "nar-rayya"
