_GCP_PROJECT_ID: "The GCP project ID where the resources are located"
_BIGQUERY_DATASET_ID: "your_name_in_lowercase_titanic"
_BIGQUERY_FACTS_TABLE_ID: "titanic_facts"
_BIGQUERY_STAGING_TABLE_ID: "titanic_raw"
_TOPIC_UPDATE_FACTS_COMPLETE: "your_name_in_lowercase-update-facts-complete"
