site_name: Closer Academy | GCP
repo_name: Closer Academy Google Cloud Platform
repo_url: https://github.com/Portugapt/closer-7th-academy

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs

watch:
- functions/

docs_dir: docs/content
nav:
- Overview: 
  - index: index.md
  - Architectures: 
    - Simple MLOps: architecture/simplemlops.md
  - Services/Resources:
    - index: services/index.md
- Create Resources: create_resources.md
- Client Libraries (Python): client_libs_py.md
- Manual Exercises:
  - Dataset: manual_exercises/titanic.md
  - Exercise 1: manual_exercises/ex1.md
  - Exercise 2: manual_exercises/ex2.md
  - Exercise 3: manual_exercises/ex3.md
  - Exercise 4: manual_exercises/ex4.md


markdown_extensions:
- footnotes
- toc:
    permalink: True
- admonition
- tables
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [functions/]
        options:
          heading_level: 3
          show_root_full_path: false
          show_root_heading: true
- search
