site_name: Closer Academy | GCP
repo_name: Closer Academy Google Cloud Platform
repo_url: https://github.com/Portugapt/closer-7th-academy

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs

watch:
- functions/

docs_dir: docs/content
nav:
- Index: index.md
- Create Resources: create_resources.md
- Client Libraries (Python): client_libs_py.md
- Manual Exercises:
  - Dataset: exercises/titanic.md
  - Exercise 1: exercises/ex1.md
  - Exercise 2: exercises/ex2.md
  - Exercise 3: exercises/ex3.md
  - Exercise 4: exercises/ex4.md


markdown_extensions:
- footnotes
- toc:
    permalink: True
- admonition
- tables
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [functions/]
        options:
          heading_level: 3
          show_root_full_path: false
          show_root_heading: true
- search
