_GCP_PROJECT_ID: "closeracademy-handson"
_GCS_BUCKET_NAME_MODELS: "your_name_in_lowercase-models"
_BIGQUERY_DATASET_ID: "jm_test_to_delete"
_BIGQUERY_TABLE_ID: "jm_test-delete-titanic-predictions"
_MODEL_LOCATION: "nar-rayya"
