_GCP_PROJECT_ID: "closeracademy-handson"
_BIGQUERY_DATASET_ID: "jm_test_to_delete"
_BIGQUERY_FACTS_TABLE_ID: "jm_test-delete-titanic_facts"
_BIGQUERY_STAGING_TABLE_ID: "jm_test-delete-titanic"
_TOPIC_UPDATE_FACTS_COMPLETE: "your_name_in_lowercase-update-facts-complete"
