_GCP_PROJECT_ID: "closeracademy-handson"
_BIGQUERY_DATASET_ID: "jmonteiro_titanic"
_BIGQUERY_FACTS_TABLE_ID: "titanic_facts"
_BIGQUERY_STAGING_TABLE_ID: "titanic_raw"
_TOPIC_UPDATE_FACTS_COMPLETE: "jmonteiro-update-facts-complete"
