_GCP_PROJECT_ID: "The GCP project ID where the resources are located"
_GCS_BUCKET_NAME_MODELS: "your_name_in_lowercase-models"
_TOPIC_TRAINING_COMPLETE: "your_name_in_lower_case-train-model-complete"
