_GCP_PROJECT_ID: "closeracademy-handson"
_BIGQUERY_DATASET_ID: "your_name_in_lowercase_titanic"
_BIGQUERY_TABLE_ID: "titanic_raw"
_TOPIC_INGESTION_COMPLETE: "your_name_in_lowercase-ingestion-complete"
